import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bita and Javad's Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.slide}>
          <div className={styles.flower}><Image layout="fill" src="/flower.svg" /></div>

          <div className={styles.title}> <span className={styles.redChar}>B</span>ita <br/> and<br/> <span className={styles.redChar}>J</span>avad's<br/> Wedding</div>
        </div>
      </main>
    </div>
  );
};

export default Home;
